name: taskproject
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1  

  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.6+1
  dio: ^3.0.8
  cached_network_image: ^2.0.0
  fluttertoast: ^3.1.3
  image_picker: ^0.6.3+1
  image_cropper: ^1.2.0
  pull_to_refresh: ^1.5.8
  flutter_image_compress: ^0.6.5+1
  flutter_cache_manager: ^1.1.3
  date_format: ^1.0.8
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
